
name: Run Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress in Cloud
        uses: cypress-io/github-action@v7
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          spec: "cypress/e2e/OzanKaraliMedium/openOzanKarali.cy.js"
          start: ""     # у тебе немає npm start
          build: ""     # і немає build