
name: Run Cypress Tests


on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Test Suite"
        required: true
        type: choice
        options:
          - Smoke
          - All
        default: Smoke


jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

       
      # ---------------------------
      # Run Smoke suite (only smoke folder)
      # ---------------------------
      - name: Run Smoke Suite
        if: ${{ github.event.inputs.suite == 'Smoke' }}
        uses: cypress-io/github-action@v7
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          spec: "cypress/e2e/OzanKaraliMedium/openOzanKarali.cy.js"
          start: ""
          build: ""

      # ---------------------------
      # Run All tests (entire e2e folder)
      # ---------------------------
      - name: Run All Tests
        if: ${{ github.event.inputs.suite == 'All' }}
        uses: cypress-io/github-action@v7
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          record: true
          spec: "cypress/e2e/OzanKaraliMedium/openOzanKarali.cy.js"
          start: ""
          build: ""
  
